### ISSUE TITLE
关于NODE版本问题

### ISSUE THREAD

**Issue by damokeris** [soraincloud/SRIC-blog#1]
你好，尊敬的soraincloud：
我注意到，您好像没有提及前端所需的NODE版本，据我所知，新的版本可能带来新的特性，同时一些的老的组件可能被弃用，所以我认为可以在README中添加相关的描述，以免因为不同node版本原因而带来不必要的麻烦QAQ

**Comment by soraincloud** [comment]
你好：
我使用的是NODE的长期支持版本进行部署开发
我会尽快在README中添加相应的描述
感谢您的提醒
: )
